### PR TITLE
Fix docs + examples

### LINKED ISSUE #134: Documentation does not build on main
Apparently, the documentation does not build on the main, but only on PRs when adding the `Run Example` label.
These are the steps in the buildkite settings
```
steps:
  - command: "buildkite-agent pipeline upload .buildkite/examples_build.yml "
    label: ":pipeline:"
    if: "build.pull_request.labels includes \"Run examples\""
    agents:
      queue: new-central
```
There is the possibility of running the pipeline on a schedule on main, do we want to do it nightly?

### LINKED ISSUE #406: Documentation fails to built
Last tagged version for docs is 0.3.3
Since then the docs fail to build.

#388 is an attempt to solve this

### PR DESCRIPTION
**Pull request by glwagner**
Supercedes #461 

Closes #406
Closes #134

### CODE REVIEW

**Comment by navidcy** [comment]
I think we should reduce the examples we literate and have in the docs.

I suggest we keep:

- one degree global
- 0.25 degree near-global
- generate_bathymetry
- one of the single-column examples
- arctic simulation (if it's ready and running?)

And we move the rest into a validation directory for now.

File: examples/one_degree_simulation.jl [hunk 1]
```diff
@@ -20,25 +20,28 @@ using ClimaOcean.ECCO: download_dataset
...
-Nx = 256
-Ny = 128
+Nx = 360
+Ny = 170
 Nz = 40
 
 r_faces = exponential_z_faces(; Nz, depth=4000, h=34)
 underlying_grid = TripolarGrid(arch; size = (Nx, Ny, Nz), z = r_faces, halo = (5, 5, 4))
 
 ## 75 interpolation passes smooth the bathymetry near Florida so that the Gulf Stream is able to flow:
```
Comment (navidcy) [inline examples/one_degree_simulation.jl:42]: the comment says 75 but we do 10

Comment (glwagner) [reply examples/one_degree_simulation.jl:42]: ill change it back to 75 when we are tready to merge. It's just expensive for testing.

**Comment by glwagner** [comment]
> I think we should reduce the examples we literate and have in the docs.
> 
> I suggest we keep:
> 
> * one degree global
> * 0.25 degree near-global
> * generate_bathymetry
> * one of the single-column examples
> * arctic simulation (if it's ready and running?)
> 
> And we move the rest into a validation directory for now.

I suggest that we don't do generate bathymetry (redundant) or arctic (considering how recently we got sea ice together)

**Comment by navidcy** [comment]
Great. I agree with the list. I'll work on making one of the single-column examples work. Which one you reckon? Station Papa?

File: examples/near_global_ocean_simulation.jl [hunk 2]
```diff
@@ -30,8 +30,7 @@ using Printf
 # The total depth of the domain is set to 6000 meters.
 # Finally, we specify the architecture for the simulation, which in this case is a GPU.
 
-arch = GPU()
-
+arch = CPU()
```
Comment (navidcy) [inline examples/near_global_ocean_simulation.jl:33]: why change back to CPU? mistake?

**Comment by glwagner** [comment]
getting this sad error https://buildkite.com/clima/climaocean-examples/builds/2862#01963217-01b7-462c-9188-f7bda6a2ef65/190-1021

File: examples/one_degree_simulation.jl [hunk 3]
```diff
@@ -15,92 +16,75 @@ using Dates
...
 
-underlying_grid = TripolarGrid(arch;
-                               size = (Nx, Ny, Nz),
-                               z = z_faces,
-                               halo = (5, 5, 4),
-                               first_pole_longitude = 70,
-                               north_poles_latitude = 55)
+z = exponential_z_faces(; Nz, depth=4000, h=34)
+# underlying_grid = TripolarGrid(arch; size = (Nx, Ny, Nz), halo = (5, 5, 4), z)
+underlying_grid = LatitudeLongitudeGrid(arch; size = (Nx, Ny, Nz), halo = (5, 5, 4), z, longitude=(0, 360), latitude=(-80, 80))
```
Comment (glwagner) [inline examples/one_degree_simulation.jl:41]:
```suggestion
underlying_grid = TripolarGrid(arch; size = (Nx, Ny, Nz), halo = (5, 5, 4), z)
# underlying_grid = LatitudeLongitudeGrid(arch; size = (Nx, Ny, Nz), halo = (5, 5, 4), z, longitude=(0, 360), latitude=(-80, 80))
```

File: .buildkite/examples_build.yml [hunk 4]
```diff
@@ -1,46 +1,43 @@
...
-  queue: new-central
-  slurm_mem: 8G
-  modules: climacommon/2024_10_10
-  slurm_time: 48:00:00
 
 env:
-  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
-  OPENBLAS_NUM_THREADS: 1
-  OMPI_MCA_opal_warn_on_missing_libcuda: 0
+  JULIA_VERSION: "1.10.8"
```
Comment (navidcy) [inline .buildkite/examples_build.yml:3]:
```suggestion
  JULIA_VERSION: "1.10.9"
```

File: .buildkite/examples_build.yml [hunk 5]
```diff
@@ -1,46 +1,43 @@
...
+  JULIA_NUM_THREADS: 8
+  CUDA_VISIBLE_DEVICES: "2" # Device for building ClimaOcean docs
 
 steps:
   - label: "initialize"
     key: "init"
+    env:
+      JULIA_DEPOT_PATH: "$TARTARUS_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
+      TEST_GROUP: "init"
+      CUDA_VISIBLE_DEVICES: "3"
```
Comment (glwagner) [inline .buildkite/examples_build.yml:17]:
```suggestion
      CUDA_VISIBLE_DEVICES: "2"
```

**Comment by navidcy** [comment]
@glwagner, so the docs build successfully in the last build but the write rights to the repo don't seem to be set up correctly?

https://buildkite.com/clima/climaocean-examples/builds/2973#019645a7-6677-4a1b-bdab-40e0706cf9c6/22-1904

**Comment by navidcy** [comment]
I noticed that you only gave *only* Read rights to the `documenter-tartarus` deploy key at https://github.com/CliMA/ClimaOceanDocumentation/settings/keys and not Read/Write as the previous deploy key above. Perhaps that's the issue?

File: examples/one_degree_simulation.jl [hunk 6]
```diff
@@ -15,92 +16,78 @@ using Dates
...
+underlying_grid = TripolarGrid(arch; size = (Nx, Ny, Nz), halo = (5, 5, 4), z)
+# underlying_grid = LatitudeLongitudeGrid(arch; size = (Nx, Ny, Nz), halo = (5, 5, 4), z, longitude=(0, 360), latitude=(-80, 80))
 
+## 75 interpolation passes smooth the bathymetry near Florida so that the Gulf Stream is able to flow:
 bottom_height = regrid_bathymetry(underlying_grid;
-                                  minimum_depth = 10,
-                                  interpolation_passes = 75, # 75 interpolation passes smooth the bathymetry near Florida so that the Gulf Stream is able to flow
-				                  major_basins = 2)
+                                  minimum_depth = 20,
+                                  interpolation_passes = 100,
```
Comment (navidcy) [inline examples/one_degree_simulation.jl:46]: why 100?

File: examples/one_degree_simulation.jl [hunk 7]
```diff
@@ -15,92 +16,78 @@ using Dates
...
-FT = ECCORestoring(temperature, grid; mask, rate=restoring_rate)
-FS = ECCORestoring(salinity,    grid; mask, rate=restoring_rate)
-forcing = (T=FT, S=FS)
+mask = LinearlyTaperedPolarMask(southern=(-80, -70), northern=(70, 90), z=(z[1], 0))
+@inline damping(x, y, z, t, u, p) = - p.r * p.mask(y, z) * u
+FT = ECCORestoring(ecco_temperature, arch; mask, rate=restoring_rate)
+FS = ECCORestoring(ecco_salinity, arch; mask, rate=restoring_rate)
+Fu = Forcing(damping, field_dependencies=:u, parameters=(r=restoring_rate; mask))
+Fv = Forcing(damping, field_dependencies=:v, parameters=(r=restoring_rate; mask))
+forcing = (T=FT, S=FS, u=Fu, v=Fv)
```
Comment (navidcy) [inline examples/one_degree_simulation.jl:62]: this looks right to me, but the docs built is complaining about something in continuous_forcing: https://buildkite.com/clima/climaocean-examples/builds/2996#0196470a-4e03-40b2-84c7-56de1e947d32/22-792

File: examples/one_degree_simulation.jl [hunk 8]
```diff
@@ -15,92 +16,78 @@ using Dates
...
+eddy_closure = Oceananigans.TurbulenceClosures.IsopycnalSkewSymmetricDiffusivity(κ_skew=1e3, κ_symmetric=1e3)
 vertical_mixing = ClimaOcean.OceanSimulations.default_ocean_closure()
-
-closure = (eddy_closure, vertical_mixing)
+horizontal_viscosity = HorizontalScalarDiffusivity(ν=2000)
+closure = (eddy_closure, horizontal_viscosity, vertical_mixing)
 
 # ### Ocean simulation
 # Now we bring everything together to construct the ocean simulation.
 # We use a split-explicit timestepping with 30 substeps for the barotropic
```
Comment (navidcy) [inline examples/one_degree_simulation.jl:77]:
```suggestion
# We use a split-explicit timestepping with 50 substeps for the barotropic
```

**Comment by navidcy** [comment]
After many months here's a docs preview!!

https://clima.github.io/ClimaOceanDocumentation/previews/PR466/

**Comment by navidcy** [comment]
With `Nz = 100` simulation blows up after 11-ish days and I noticed in the progress report that e goes quite negative from time to time. Are we doing sub stepping for TKE here? Do we need to tweak anything? I'm trying with `Nz = 50` to see if the problem goes away.

**Comment by navidcy** [comment]
> With `Nz = 100` simulation blows up after 11-ish days and I noticed in the progress report that e goes quite negative from time to time. Are we doing sub stepping for TKE here? Do we need to tweak anything? I'm trying with `Nz = 50` to see if the problem goes away.

I guess this is related to what @simone-silvestri was mentioning about find Δz implying bigger vertical velocities and requiring smaller timestep to avoid hitting CFL limits.

**Comment by glwagner** [comment]
I don't like `generate_bathymetry` because it documents a workflow we want to change. Can we leave it out for now?

**Comment by glwagner** [comment]
there's no arctic simulation to include as an example so lets save for another PR

**Comment by navidcy** [comment]
leave it out from where? this PR? sure!
I think the only changes in this PR is that we drop this optimisation step with the extra passes only if resolution is finer or not...

**Comment by glwagner** [comment]
I think this is basically good to go if the docs build

**Review by navidcy — APPROVED** [review]

**Comment by navidcy** [comment]
few previews + videos from previous build here:

https://clima.github.io/ClimaOceanDocumentation/previews/PR466/literated/one_degree_simulation/

https://clima.github.io/ClimaOceanDocumentation/previews/PR466/literated/near_global_ocean_simulation/

https://clima.github.io/ClimaOceanDocumentation/previews/PR466/literated/single_column_os_papa_simulation

**Comment by glwagner** [comment]
woo!

**Comment by navidcy** [comment]
Omg woooooooo
