### PR TITLE
Add to docstring for `download_dataset` about MPI downloading plus fix for Copernicus

### LINKED ISSUE #523: Documentation does not clarify if `download` functions are MPI safe
I searched for `download` in the docs trying to see if there's anything I have to worry about when running my code with MPI, but couldn't find any mention about this.

### PR DESCRIPTION
**Pull request by glwagner**
Closes #523

### CODE REVIEW

File: ext/ClimaOceanPythonCallExt.jl [hunk 1]
```diff
@@ -3,6 +3,7 @@ module ClimaOceanPythonCallExt
 using ClimaOcean
 using CondaPkg
 using PythonCall
+using Oceananigans.DistributedComputations: @root
```
Comment (glwagner) [inline ext/ClimaOceanPythonCallExt.jl:6]:
```suggestion
using Oceananigans
```

File: ext/ClimaOceanPythonCallExt.jl [hunk 2]
```diff
@@ -61,7 +62,8 @@ function download_dataset(meta::CopernicusMetadata, grid=nothing; skip_existing
 
     additional_kw = NamedTuple(name => value for (name, value) in additional_kw)
     kw = merge(kw, datetime_kw, lon_kw, lat_kw, z_kw, additional_kw)
-    toolbox.subset(; kw...)
+
+    @root toolbox.subset(; kw...)
```
Comment (glwagner) [inline ext/ClimaOceanPythonCallExt.jl:66]:
```suggestion
    Oceananigans.DistributedComputations.@root toolbox.subset(; kw...)
```

**Review by Sbozzolo — APPROVED** [review]
Thank you!
