### PR TITLE
Fix axis labels in near-global example + Docstring rendering + Few typos

### LINKED ISSUE #289: Incorret plot labels in "Near Global Ocean Simulation"
https://clima.github.io/ClimaOceanDocumentation/stable/literated/near_global_ocean_simulation/

The plots here show latitude going from 0 to 600 and longitude from 0 to more than 1250.

### PR DESCRIPTION
**Pull request by navidcy**
Closes #289

Also adds a title with the time in the near-global example figure & animation.

https://clima.github.io/ClimaOceanDocumentation/previews/PR315/literated/near_global_ocean_simulation/#A-pretty-movie

### CODE REVIEW

File: src/Bathymetry.jl [hunk 1]
```diff
@@ -32,65 +32,70 @@ end
...
 
-- `target_grid`: grid to interpolate onto
+- `target_grid`: grid to interpolate the bathymetry onto.
 
 Keyword Arguments
 =================
 
-- `height_above_water`: limits the maximum height of above-water topography (where h > 0). If
-                        `nothing` the original topography is retained
+- `height_above_water`: limits the maximum height of above-water topography (where ``h > 0``).
```
Comment (simone-silvestri) [inline src/Bathymetry.jl:54]:
```suggestion
- `height_above_water`: limits the maximum height of above-water topography (where ``h > 0``) before inetrpolating.
```

**Review by simone-silvestri — APPROVED** [review]
