### PR TITLE
Persist FractionalIndices with two separate arrays for `i, j`

### LINKED ISSUE #370: There is an issue with `StateExchanger` on GPUs
this snipper down here on main

```julia 
using ClimaOcean
using ClimaSeaIce
using Oceananigans
using Oceananigans.Grids
using Oceananigans.Units
using Oceananigans.OrthogonalSphericalShellGrids
using ClimaOcean.OceanSimulations
using ClimaOcean.ECCO
using ClimaOcean.ECCO: all_ECCO_dates
using Printf

r_faces = ClimaOcean.exponential_z_faces(; Nz=30, h=10, depth=3000)
z_faces = MutableVerticalDiscretization(r_faces)

Nx = 180 # longitudinal direction -> 250 points is about 1.5ᵒ resolution
Ny = 180 # meridional direction -> same thing, 48 points is about 1.5ᵒ resolution
Nz = length(r_faces) - 1

grid = RotatedLatitudeLongitudeGrid(GPU(), size = (Nx, Ny, Nz), 
                                           latitude = (-45, 45),
                                           longitude = (-45, 45),
                                           z = r_faces,
                                           north_pole = (180, 0),
                                           halo = (5, 5, 4),
                                           topology = (Bounded, Bounded, Bounded))

bottom_height = regrid_bathymetry(grid; minimum_depth=15, major_basins=1)
grid = ImmersedBoundaryGrid(grid, GridFittedBottom(bottom_height))
momentum_advection = WENOVectorInvariant(order=5) 
tracer_advection   = Centered()

free_surface = SplitExplicitFreeSurface(grid; cfl=0.7) 

ocean = ocean_simulation(grid; 
                         momentum_advection, 
                         tracer_advection, 
                         free_surface)

sea_ice = sea_ice_simulation(grid; dynamics=nothing, advection=nothing) 
atmosphere = JRA55PrescribedAtmosphere(GPU(); backend=JRA55NetCDFBackend(40))
radiation  = Radiation()
arctic = OceanSeaIceModel(ocean, sea_ice; atmosphere, radiation)
arctic = Simulation(arctic, Δt=600, stop_time=365days)
```
fails with a scalar indexing error
```
ERROR: Scalar indexing is disallowed.
Invocation of getindex resulted in scalar indexing of a GPU array.
This is typically caused by calling an iterating implementation of a method.
Such implementations *do not* execute on the GPU, but very slowly on the CPU,
and therefore should be avoided.

If you want to allow scalar iteration, use `allowscalar` or `@allowscalar`
to enable scalar iteration globally or for the operations in question.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] errorscalar(op::String)
    @ GPUArraysCore ~/.julia/packages/GPUArraysCore/aNaXo/src/GPUArraysCore.jl:151
  [3] _assertscalar(op::String, behavior::GPUArraysCore.ScalarIndexing)
    @ GPUArraysCore ~/.julia/packages/GPUArraysCore/aNaXo/src/GPUArraysCore.jl:124
  [4] assertscalar(op::String)
    @ GPUArraysCore ~/.julia/packages/GPUArraysCore/aNaXo/src/GPUArraysCore.jl:112
  [5] getindex
    @ ~/.julia/packages/GPUArrays/uiVyU/src/host/indexing.jl:50 [inlined]
  [6] getindex
    @ ~/.julia/packages/OffsetArrays/HLmxQ/src/OffsetArrays.jl:435 [inlined]
  [7] getindex
    @ ./subarray.jl:323 [inlined]
  [8] fractional_x_index
    @ ~/.julia/packages/Oceananigans/wwTjd/src/Fields/interpolate.jl:129 [inlined]
  [9] _fractional_indices
    @ ~/.julia/packages/Oceananigans/wwTjd/src/Fields/interpolate.jl:233 [inlined]
 [10] FractionalIndices
    @ ~/.julia/packages/Oceananigans/wwTjd/src/Fields/interpolate.jl:207 [inlined]
 [11] ClimaOcean.OceanSeaIceModels.InterfaceComputations.StateExchanger(ocean::Simulation{…}, atmosphere::PrescribedAtmosphere{…})
    @ ClimaOcean.OceanSeaIceModels.InterfaceComputations ~/development/ClimaOcean.jl/src/OceanSeaIceModels/InterfaceComputations/component_interfaces.jl:86
 [12] ClimaOcean.OceanSeaIceModels.InterfaceComputations.ComponentInterfaces(atmosphere::PrescribedAtmosphere{…}, ocean::Simulation{…}, sea_ice::Simulation{…}; radiation::Radiation{…}, freshwater_density::Int64, atmosphere_ocean_flux_formulation::SimilarityTheoryFluxes{…}, atmosphere_sea_ice_flux_formulation::ClimaOcean.OceanSeaIceModels.InterfaceComputations.CoefficientBasedFluxes{…}, atmosphere_ocean_interface_temperature::BulkTemperature, atmosphere_ocean_interface_specific_humidity::ClimaOcean.OceanSeaIceModels.InterfaceComputations.SpecificHumidityFormulation{…}, atmosphere_sea_ice_interface_temperature::SkinTemperature{…}, ocean_reference_density::Float64, ocean_heat_capacity::Float64, ocean_temperature_units::ClimaOcean.OceanSeaIceModels.InterfaceComputations.DegreesCelsius, sea_ice_temperature_units::ClimaOcean.OceanSeaIceModels.InterfaceComputations.DegreesCelsius, sea_ice_reference_density::Float64, sea_ice_heat_capacity::Float64)
    @ ClimaOcean.OceanSeaIceModels.InterfaceComputations ~/development/ClimaOcean.jl/src/OceanSeaIceModels/InterfaceComputations/component_interfaces.jl:303
 [13] OceanSeaIceModel(ocean::Simulation{…}, sea_ice::Simulation{…}; atmosphere::PrescribedAtmosphere{…}, radiation::Radiation{…}, clock::Clock{…}, ocean_reference_density::Float64, ocean_heat_capacity::Float64, sea_ice_reference_density::Float64, sea_ice_heat_capacity::Float64, interfaces::Nothing)
    @ ClimaOcean.OceanSeaIceModels ~/development/ClimaOcean.jl/src/OceanSeaIceModels/ocean_sea_ice_model.jl:129
 [14] top-level scope
    @ REPL[30]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

### PR DESCRIPTION
**Pull request by simone-silvestri**
The fact that GPU tests do not run is starting to have quite a price on the development process.

close #370

### CODE REVIEW

File: src/OceanSeaIceModels/InterfaceComputations/component_interfaces.jl [hunk 1]
```diff
@@ -81,11 +80,9 @@ function StateExchanger(ocean::Simulation, atmosphere)
     Nx, Ny, Nz = size(exchange_grid)
 
     # Make an array of FractionalIndices
-    kᴺ = size(exchange_grid, 3)
-    @allowscalar X1 = _node(1, 1, kᴺ + 1, exchange_grid, c, c, f)
-    i1 = FractionalIndices(X1, atmosphere.grid, c, c, nothing)
-    frac_indices_data = [deepcopy(i1) for i=1:Nx+2, j=1:Ny+2, k=1:1]
-    frac_indices = OffsetArray(frac_indices_data, -1, -1, 0)
+    FT = eltype(exchange_grid)
+    frac_indices = [FractionalIndices(one(FT), one(FT), one(FT)) for i=1:Nx+2, j=1:Ny+2, k=1:1]
```
Comment (glwagner) [inline src/OceanSeaIceModels/InterfaceComputations/component_interfaces.jl:84]: This isn't correct for all grids

**Comment by glwagner** [comment]
> The fact that GPU tests do not run is starting to have quite a price on the development process.
> 
> close #370

I don't agree that its "starting" to have a price. From the very moment the tests stop working, way pay the price. It doesn't take any time.

**Review by glwagner — APPROVED** [review]
